"""Predict neural responses from spatial and temporal receptive fields.

This script combines a spatial receptive field (fit from images) with a temporal
receptive field (fit from time series data) to predict neural responses to a stimulus.

Usage:
    python predict_resp.py <stimulus.tif|csv> <srf_params.json> <trf_params.csv> \
        [--roi N --centers-csv file] [--gcamp-mapping file] --output <output.npy>

Input formats:
    stimulus: 3D TIFF stack (frames, height, width) OR CSV file with stimulus patterns
        - TIFF: 3D stack (frames, height, width) or 2D image
        - CSV: Columns 0-2 are metadata, columns 3:-1 are flattened stimulus (must be perfect square)
    srf_params.json: JSON file with spatial RF parameters (output from fit_srf.py)
    trf_params.csv: CSV file with temporal RF (columns: time, filter_value)

Optional arguments:
    --roi N: ROI number to center the SRF (requires --centers-csv)
    --centers-csv: Path to centers_and_contiguous_sizes.csv for ROI coordinates
    --gcamp-mapping: Path to Gcamp-stim-mapped.csv to extract recording start/stop frames
    --stimulus-rate: Stimulus frame rate in Hz (default: 30.0)

Output:
    Predicted response trace as a 1D numpy array (time points)

Examples:
    # Without GCaMP mapping (uses all stimulus frames)
    python predict_resp.py stimulus.csv srf_params.json trf_params.csv --plot
    
    # With GCaMP mapping to extract only recorded frames
    python predict_resp.py stimulus.csv srf_params.json trf_params.csv \
        --gcamp-mapping measurements/Gcamp-stim-mapped.csv --plot
    
    # With ROI centering and GCaMP mapping
    python predict_resp.py stimulus.csv srf_params.json trf_params.csv \
        --roi 5 --centers-csv centers_and_contiguous_sizes.csv \
        --gcamp-mapping measurements/Gcamp-stim-mapped.csv --output pred.npy
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import numpy as np
import pandas as pd

try:
    import tifffile
except ImportError as exc:
    raise ImportError(
        "tifffile is required to read TIFF files. Install with: pip install tifffile"
    ) from exc


def gaussian_2d(
    xy: tuple[np.ndarray, np.ndarray],
    amp: float,
    x0: float,
    y0: float,
    sigma_x: float,
    sigma_y: float,
    offset: float,
) -> np.ndarray:
    """2D Gaussian model."""
    x, y = xy
    exponent = ((x - x0) ** 2) / (2 * sigma_x**2) + ((y - y0) ** 2) / (2 * sigma_y**2)
    gaussian = amp * np.exp(-exponent)
    return offset + gaussian


def dog_2d(
    xy: tuple[np.ndarray, np.ndarray],
    amp_center: float,
    x0: float,
    y0: float,
    sigma_x_center: float,
    sigma_y_center: float,
    amp_surround: float,
    sigma_x_surround: float,
    sigma_y_surround: float,
    offset: float,
) -> np.ndarray:
    """Difference of Gaussians model."""
    x, y = xy
    exponent_center = ((x - x0) ** 2) / (2 * sigma_x_center**2) + ((y - y0) ** 2) / (2 * sigma_y_center**2)
    center = amp_center * np.exp(-exponent_center)
    exponent_surround = ((x - x0) ** 2) / (2 * sigma_x_surround**2) + ((y - y0) ** 2) / (2 * sigma_y_surround**2)
    surround = amp_surround * np.exp(-exponent_surround)
    return offset + center + surround


def load_srf_params(json_path: Path) -> dict:
    """Load spatial RF parameters from JSON file.
    
    Args:
        json_path: Path to JSON file generated by fit_srf.py
        
    Returns:
        Dictionary with 'model_type' and 'parameters' keys
    """
    with open(json_path, 'r') as f:
        params = json.load(f)
    
    # Default to Gaussian if model_type not specified
    if 'model_type' not in params:
        params['model_type'] = 'Gaussian'
    
    return params


def load_trf_params(csv_path: Path, time_min: float = -1.5, time_max: float = 0.0) -> tuple[np.ndarray, np.ndarray]:
    """Load temporal RF parameters from CSV file and crop to specified time range.
    
    Expected CSV format:
    - First column: time (in seconds)
    - Second column: filter value
    
    Args:
        csv_path: Path to CSV file with temporal RF
        time_min: Minimum time value to keep (default: -1.5 seconds)
        time_max: Maximum time value to keep (default: 0.0 seconds)
        
    Returns:
        Tuple of (time_points, filter_values) cropped to [time_min, time_max]
    """
    df = pd.read_csv(csv_path)
    
    # Get first two columns regardless of header names
    time = df.iloc[:, 0].values
    trf_filter = df.iloc[:, 1].values
    
    # Filter to specified time range
    mask = (time >= time_min) & (time <= time_max)
    time_cropped = time[mask]
    trf_cropped = trf_filter[mask]
    
    print(f"TRF: Cropped from {time.min():.2f} to {time.max():.2f}s -> {time_cropped.min():.2f} to {time_cropped.max():.2f}s")
    print(f"TRF: {len(time)} points -> {len(time_cropped)} points")
    
    return time_cropped, trf_cropped


def load_stimulus_from_csv(csv_path: Path) -> np.ndarray:
    """Load and reconstruct stimulus from CSV file.
    
    CSV format (like align_stim.py):
    - Columns 0-2: metadata (timestamp, etc.)
    - Columns 3 to -1: raw stimulus values (flattened spatial pattern)
    - Last column: frame index or metadata
    
    Raw stimulus values must form a perfect square when flattened into 2D.
    
    Args:
        csv_path: Path to CSV file with stimulus patterns
        
    Returns:
        3D numpy array (frames, height, width)
    """
    rows = []
    with open(csv_path, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            rows.append(row)
    
    # Extract stimulus values from columns 3 to -1
    patterns = []
    for row in rows:
        # Skip header row if it contains non-numeric values
        try:
            vec = [float(v) for v in row[3:-1]]
            patterns.append(vec)
        except (ValueError, IndexError):
            # Skip header rows or malformed rows
            continue
    
    patterns = np.array(patterns, dtype=np.float32)
    
    # Check that stimulus forms a perfect square
    num_values = patterns.shape[1]
    dim = int(np.sqrt(num_values))
    
    if dim * dim != num_values:
        raise ValueError(
            f"Expected square number of stimulus values, got {num_values} in {csv_path}. "
            f"sqrt({num_values}) = {np.sqrt(num_values)}"
        )
    
    # Reshape each flat pattern into a 2D image
    stimulus_3d = patterns.reshape(patterns.shape[0], dim, dim)
    
    return stimulus_3d


def load_gcamp_stim_mapping(mapping_csv: Path, roi: int | None = None) -> tuple[int, int]:
    """Load GCaMP-stimulus mapping to determine recording start and stop frames.
    
    The Gcamp-stim-mapped.csv file contains:
    - ROI: ROI number
    - frame: GCaMP frame number (0-indexed)
    - stim_frame: stimulus frame number that corresponds to this GCaMP frame
    - stim_global_time: timestamp of the stimulus
    - dff: delta F/F response
    
    This function finds the minimum and maximum stimulus frames that were recorded.
    
    Args:
        mapping_csv: Path to Gcamp-stim-mapped.csv file
        roi: Optional ROI number to filter by (if None, uses all ROIs)
        
    Returns:
        Tuple of (stim_frame_start, stim_frame_end) as recorded in GCaMP
    """
    df = pd.read_csv(mapping_csv)
    
    # Filter by ROI if specified
    if roi is not None:
        df = df[df['ROI'] == roi]
    
    if df.empty:
        raise ValueError(f"No data found in {mapping_csv}" + 
                        (f" for ROI {roi}" if roi is not None else ""))
    
    stim_frame_start = int(df['stim_frame'].min())
    stim_frame_end = int(df['stim_frame'].max())
    
    print(f"Recording spans stimulus frames {stim_frame_start} to {stim_frame_end}")
    print(f"  Total stimulus frames in recording: {stim_frame_end - stim_frame_start + 1}")
    
    return stim_frame_start, stim_frame_end


def load_gcamp_stim_mapping_full(mapping_csv: Path, roi: int | None = None) -> pd.DataFrame:
    """Load full GCaMP-stimulus mapping DataFrame.
    
    Args:
        mapping_csv: Path to Gcamp-stim-mapped.csv file
        roi: Optional ROI number to filter by (if None, uses all ROIs)
        
    Returns:
        DataFrame with ROI, frame, stim_frame, stim_global_time, dff columns
    """
    df = pd.read_csv(mapping_csv)
    
    # Filter by ROI if specified
    if roi is not None:
        df = df[df['ROI'] == roi]
    
    if df.empty:
        raise ValueError(f"No data found in {mapping_csv}" + 
                        (f" for ROI {roi}" if roi is not None else ""))
    
    return df


def load_roi_center(centers_csv: Path, roi: int, sample_name: str | None = None) -> tuple[float, float]:
    """Load ROI center coordinates from CSV file (like find_trf.py).
    
    The centers CSV has columns: file, center_row, center_col, center_zscore, contiguous_size
    where "file" contains mask filenames that can be keyed by ROI.
    
    Args:
        centers_csv: Path to centers_and_contiguous_sizes.csv
        roi: ROI number to look up
        sample_name: Optional sample name to filter by
        
    Returns:
        Tuple of (center_row, center_col) - note these are spatial coordinates
    """
    centers_map = {}
    
    # Build centers map from CSV using DictReader (like find_trf.py)
    with centers_csv.open("r", newline="") as fp:
        reader = csv.DictReader(fp)
        for row in reader:
            file_path = row.get("file", "")
            center_row = row.get("center_row")
            center_col = row.get("center_col")
            
            if not file_path or center_row is None or center_col is None:
                continue
            
            try:
                r = int(float(center_row))
                c = int(float(center_col))
            except ValueError:
                continue
            
            # Store by file stem (like find_trf.py does)
            stem = Path(file_path).stem
            centers_map[stem] = (r, c)
    
    if not centers_map:
        raise ValueError(f"No valid center entries found in {centers_csv}")
    
    # Build potential lookup keys for this ROI
    potential_keys = [
        f"{sample_name}_roi_{roi}" if sample_name else None,
        f"roi_{roi}",
        f"ROI_{roi}",
        f"{sample_name}-roi-{roi}" if sample_name else None,
        f"{sample_name}-{roi}" if sample_name else None,
        str(roi),
    ]
    
    # Try each potential key
    for key in potential_keys:
        if key is None:
            continue
        
        # Exact match
        if key in centers_map:
            r, c = centers_map[key]
            print(f"Found center for '{key}': row={r}, col={c}")
            return (r, c)
        
        # Substring match (for keys like "260416_fly2-z1_roi_25_mask" -> look for "260416_fly2-z1_roi_25")
        for map_key, (r, c) in centers_map.items():
            if key in map_key:
                print(f"Found center for '{map_key}': row={r}, col={c}")
                return (r, c)
    
    # If nothing found, print available keys for debugging
    print(f"Available keys in centers map: {list(centers_map.keys())[:5]}...")
    raise ValueError(f"Could not find center for ROI {roi}" + (f" in sample {sample_name}" if sample_name else ""))


def extract_sample_name_from_path(stim_path: Path) -> str:
    """Extract sample name from stimulus file path.
    
    Expected path structure: .../sample_name/stim_files/...
    
    Args:
        stim_path: Path to stimulus file
        
    Returns:
        Sample name directory
    """
    parts = stim_path.parts
    
    # Look for 'stim_files' directory and get parent
    for i, part in enumerate(parts):
        if part == 'stim_files' and i > 0:
            return parts[i - 1]
    
    # Fallback: return the parent directory of the stim file
    return stim_path.parent.parent.name


def generate_spatial_rf(shape: tuple[int, int], srf_params: dict, 
                       roi_center: tuple[float, float] | None = None) -> np.ndarray:
    """Generate 2D spatial receptive field from parameters.
    
    Args:
        shape: (height, width) of the receptive field image
        srf_params: Dictionary with spatial RF parameters
        roi_center: Optional (x_center, y_center) to override the fitted center
        
    Returns:
        2D array of the spatial receptive field
    """
    ny, nx = shape
    y_idx, x_idx = np.indices((ny, nx))
    xy = (x_idx, y_idx)
    
    params = srf_params['parameters'].copy()
    model_type = srf_params.get('model_type', 'Gaussian')
    
    # Override center if ROI center provided
    if roi_center is not None:
        x_center, y_center = roi_center
        params['x0'] = x_center
        params['y0'] = y_center
        print(f"Centering SRF at ROI position: ({x_center:.1f}, {y_center:.1f})")
    
    if model_type == 'Gaussian':
        srf = gaussian_2d(
            xy,
            amp=params['amplitude'],
            x0=params['x0'],
            y0=params['y0'],
            sigma_x=params['sigma_x'],
            sigma_y=params['sigma_y'],
            offset=params['offset'],
        )
    elif model_type == 'DoG':
        srf = dog_2d(
            xy,
            amp_center=params['amp_center'],
            x0=params['x0'],
            y0=params['y0'],
            sigma_x_center=params['sigma_x_center'],
            sigma_y_center=params['sigma_y_center'],
            amp_surround=params['amp_surround'],
            sigma_x_surround=params['sigma_x_surround'],
            sigma_y_surround=params['sigma_y_surround'],
            offset=params['offset'],
        )
    else:
        raise ValueError(f"Unknown model type: {model_type}")
    
    return srf


def extract_spatial_response(stimulus_frame: np.ndarray, srf: np.ndarray) -> float:
    """Extract spatial response by multiplying stimulus with SRF and summing.
    
    Args:
        stimulus_frame: 2D stimulus image
        srf: 2D spatial receptive field
        
    Returns:
        Scalar response value (sum of element-wise product)
    """
    # Ensure same shape
    if stimulus_frame.shape != srf.shape:
        raise ValueError(
            f"Stimulus frame shape {stimulus_frame.shape} does not match "
            f"SRF shape {srf.shape}"
        )
    
    # Extract response as weighted sum
    response = np.sum(stimulus_frame * srf)
    return response


def bin_stimulus_by_gcamp_frames(stimulus: np.ndarray, gcamp_mapping: pd.DataFrame, 
                                   stim_frame_start: int) -> np.ndarray:
    """Bin stimulus frames based on GCaMP frame indices from the mapping.
    
    For each GCaMP frame, determine which stimulus frames it spans and average them.
    
    Args:
        stimulus: 3D stimulus array (frames, height, width) - should be the extracted range
        gcamp_mapping: DataFrame with 'stim_frame' column (stimulus frame indices)
        stim_frame_start: Starting stimulus frame index (for offset)
        
    Returns:
        Binned stimulus array matching the number of GCaMP frames
    """
    # Get stimulus frame indices for each GCaMP frame
    stim_frames = gcamp_mapping['stim_frame'].values
    
    # Determine bin boundaries
    # Each GCaMP frame corresponds to a stimulus frame; bin between consecutive mappings
    num_gcamp_frames = len(stim_frames)
    binned_stimulus = []
    
    for i in range(num_gcamp_frames):
        # Get stimulus frame index for this GCaMP frame
        current_stim_frame = stim_frames[i]
        
        # Determine next boundary (or end of stimulus)
        if i < num_gcamp_frames - 1:
            next_stim_frame = stim_frames[i + 1]
        else:
            next_stim_frame = stim_frames[i] + 1
        
        # Convert to local stimulus array indices (relative to stim_frame_start)
        start_idx = current_stim_frame - stim_frame_start
        end_idx = next_stim_frame - stim_frame_start
        
        # Ensure indices are within bounds
        start_idx = max(0, start_idx)
        end_idx = min(stimulus.shape[0], end_idx)
        
        if start_idx < stimulus.shape[0]:
            # Average stimulus frames in this bin
            bin_stim = stimulus[start_idx:end_idx].mean(axis=0)
            binned_stimulus.append(bin_stim)
    
    binned_stimulus = np.array(binned_stimulus)
    
    print(f"Stimulus binned by GCaMP frames: {stimulus.shape[0]} frames -> {len(binned_stimulus)} GCaMP frames")
    
    return binned_stimulus


def bin_stimulus(stimulus: np.ndarray, stimulus_rate: float, time_bin_size: float = 0.1) -> np.ndarray:
    """Bin stimulus frames into time bins like align_stim.py does.
    
    Args:
        stimulus: 3D stimulus array (frames, height, width)
        stimulus_rate: Frame rate in Hz
        time_bin_size: Size of each time bin in seconds (default: 0.1)
        
    Returns:
        Binned stimulus array (time_bins, height, width)
    """
    # Calculate how many frames per bin
    frames_per_bin = stimulus_rate * time_bin_size
    
    if not np.isclose(frames_per_bin, round(frames_per_bin), atol=1e-9):
        print(f"Warning: frames_per_bin={frames_per_bin} is not an integer. Rounding...")
    
    frames_per_bin = int(round(frames_per_bin))
    
    # Calculate number of complete bins
    num_frames = stimulus.shape[0]
    num_bins = num_frames // frames_per_bin
    
    if num_frames % frames_per_bin != 0:
        print(f"Warning: {num_frames} frames not divisible by {frames_per_bin} frames/bin")
        print(f"  Discarding last {num_frames % frames_per_bin} frames")
    
    # Reshape and average
    stimulus_cropped = stimulus[:num_bins * frames_per_bin]
    stimulus_reshaped = stimulus_cropped.reshape(num_bins, frames_per_bin, *stimulus.shape[1:])
    binned_stimulus = stimulus_reshaped.mean(axis=1)
    
    print(f"Stimulus binned from {stimulus.shape[0]} frames to {num_bins} bins")
    print(f"  ({frames_per_bin} frames per bin, time_bin_size={time_bin_size}s at {stimulus_rate}Hz)")
    
    return binned_stimulus


def crop_and_rotate_stimulus(stimulus: np.ndarray, row_slice: slice = slice(8, 21), 
                               col_slice: slice = slice(None, 15)) -> np.ndarray:
    """Crop and rotate stimulus like align_stim.py does.
    
    Args:
        stimulus: 3D stimulus array (frames, height, width)
        row_slice: Row slice for cropping (default: 8:21)
        col_slice: Column slice for cropping (default: :15)
        
    Returns:
        Cropped and rotated stimulus (frames, new_height, new_width)
    """
    # Crop: extract specified rows and columns
    stimulus_cropped = stimulus[:, row_slice, col_slice]
    print(f"Stimulus after cropping: {stimulus_cropped.shape}")
    
    # Rotate by 90 degrees (k=1) on axes (1, 2) - the spatial axes
    stimulus_rotated = np.rot90(stimulus_cropped, k=1, axes=(1, 2))
    print(f"Stimulus after rotation: {stimulus_rotated.shape}")
    
    return stimulus_rotated


def create_spatiotemporal_rf(srf: np.ndarray, trf_filter: np.ndarray) -> np.ndarray:
    """Create a combined spatiotemporal receptive field from SRF and TRF.
    
    Args:
        srf: 2D spatial receptive field (height, width)
        trf_filter: 1D temporal filter (time_steps,)
        
    Returns:
        3D spatiotemporal receptive field (time_steps, height, width)
    """
    # Use outer product: trf_filter[:, newaxis, newaxis] * srf
    # This creates (time_steps, height, width) array
    st_rf = trf_filter[:, np.newaxis, np.newaxis] * srf
    
    return st_rf


def convolve_spatiotemporal(stimulus: np.ndarray, st_rf: np.ndarray) -> np.ndarray:
    """Convolve stimulus with spatiotemporal receptive field.
    
    Args:
        stimulus: 3D stimulus array (frames, height, width)
        st_rf: 3D spatiotemporal RF (time_steps, height, width)
        
    Returns:
        1D predicted response trace
    """
    num_time_steps = st_rf.shape[0]
    num_stim_frames = stimulus.shape[0]
    
    # Convolve along time dimension
    # For each time step, compute the dot product of stimulus window with ST-RF
    predicted = np.zeros(num_stim_frames - num_time_steps + 1, dtype=np.float32)
    
    for t in range(len(predicted)):
        # Extract stimulus window matching ST-RF temporal extent
        stim_window = stimulus[t:t + num_time_steps]  # (time_steps, height, width)
        
        # Compute spatiotemporal dot product
        predicted[t] = np.sum(stim_window * st_rf)
    
    return predicted


def predict_responses(
    stimulus: np.ndarray,
    srf: np.ndarray,
    trf_time: np.ndarray,
    trf_filter: np.ndarray,
    stimulus_rate: float = 10.0,
) -> np.ndarray:
    """Predict neural responses from stimulus using combined spatiotemporal RF.
    
    Args:
        stimulus: 3D stimulus array (frames, height, width)
        srf: 2D spatial receptive field
        trf_time: Time points of temporal filter
        trf_filter: Temporal filter values
        stimulus_rate: Frame rate of stimulus in Hz
        
    Returns:
        1D array of predicted responses
    """
    if stimulus.ndim != 3:
        raise ValueError(f"Expected 3D stimulus (frames, height, width), got {stimulus.ndim}D")
    
    # Create combined spatiotemporal receptive field
    st_rf = create_spatiotemporal_rf(srf, trf_filter)
    print(f"Created spatiotemporal RF: {st_rf.shape}")
    
    # Convolve stimulus with spatiotemporal RF
    predicted = convolve_spatiotemporal(stimulus, st_rf)
    
    return predicted


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Predict neural responses from spatial and temporal receptive fields."
    )
    parser.add_argument(
        "stimulus",
        type=Path,
        help="Path to stimulus file (TIFF stack or CSV with patterns)",
    )
    parser.add_argument(
        "srf_params",
        type=Path,
        help="Path to spatial RF parameters JSON file",
    )
    parser.add_argument(
        "trf_params",
        type=Path,
        help="Path to temporal RF parameters CSV file",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Optional path to save predicted responses as .npy",
    )
    parser.add_argument(
        "--roi",
        type=int,
        default=None,
        help="ROI number to use for centering the SRF",
    )
    parser.add_argument(
        "--centers-csv",
        type=Path,
        default='../all_Mi1/centers_and_contiguous_sizes.csv',
        help="Path to centers_and_contiguous_sizes.csv for ROI centering",
    )
    parser.add_argument(
        "--stimulus-rate",
        type=float,
        default=20,
        help="Stimulus frame rate in Hz (default: 30.0)",
    )
    parser.add_argument(
        "--plot",
        action="store_true",
        help="Display predicted responses and spatial RF",
    )
    parser.add_argument(
        "--gcamp-mapping",
        type=Path,
        default='../all_Mi1/260416_fly2-z1/measurements/Gcamp-stim-mapped.csv',
        help="Path to Gcamp-stim-mapped.csv to extract recording start/stop frames",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    
    # Validate input files
    if not args.stimulus.exists():
        raise FileNotFoundError(f"Stimulus file not found: {args.stimulus}")
    if not args.srf_params.exists():
        raise FileNotFoundError(f"SRF parameters file not found: {args.srf_params}")
    if not args.trf_params.exists():
        raise FileNotFoundError(f"TRF parameters file not found: {args.trf_params}")
    
    print("Loading data...")
    
    # Load stimulus from TIFF or CSV
    if args.stimulus.suffix.lower() in ['.csv']:
        print("Loading stimulus from CSV...")
        stimulus = load_stimulus_from_csv(args.stimulus)
    else:
        print("Loading stimulus from TIFF...")
        stimulus = tifffile.imread(args.stimulus).astype(float)
        if stimulus.ndim == 2:
            stimulus = stimulus[np.newaxis, :, :]  # Convert to 3D
    print(f"Full stimulus shape: {stimulus.shape}")
    
    # Extract recording frames if GCaMP mapping is provided
    effective_rate = args.stimulus_rate
    gcamp_mapping_df = None
    stim_frame_start = 0
    
    if args.gcamp_mapping is not None:
        if not args.gcamp_mapping.exists():
            raise FileNotFoundError(f"GCaMP mapping file not found: {args.gcamp_mapping}")
        
        # Load full mapping for binning
        gcamp_mapping_df = load_gcamp_stim_mapping_full(args.gcamp_mapping, roi=args.roi)
        stim_frame_start, stim_frame_end = gcamp_mapping_df['stim_frame'].min(), gcamp_mapping_df['stim_frame'].max()
        
        # Extract only the stimulus frames that were recorded
        stimulus = stimulus[stim_frame_start:stim_frame_end+1]
        print(f"Extracted stimulus frames {stim_frame_start} to {stim_frame_end}")
        print(f"Extracted stimulus shape: {stimulus.shape}")
    
    # Crop and rotate stimulus like align_stim.py does
    print("Cropping and rotating stimulus...")
    stimulus = crop_and_rotate_stimulus(stimulus, row_slice=slice(8, 21), col_slice=slice(None, 15))
    
    # Bin stimulus based on GCaMP frame indices or uniform binning
    print("Binning stimulus...")
    if gcamp_mapping_df is not None:
        stimulus = bin_stimulus_by_gcamp_frames(stimulus, gcamp_mapping_df, stim_frame_start)
    else:
        time_bin_size = 0.1  # Match align_stim.py
        stimulus = bin_stimulus(stimulus, stimulus_rate=args.stimulus_rate, time_bin_size=time_bin_size)
    
    # Load spatial RF parameters
    srf_params = load_srf_params(args.srf_params)
    print(f"Spatial RF model type: {srf_params.get('model_type', 'Gaussian')}")
    
    # Load temporal RF parameters
    trf_time, trf_filter = load_trf_params(args.trf_params)
    print(f"Temporal RF: {len(trf_filter)} points, duration {trf_time[-1]:.3f}s")
    
    # Load ROI center if specified
    roi_center = None
    if args.roi is not None:
        if args.centers_csv is None:
            raise ValueError("--centers-csv must be provided when using --roi")
        if not args.centers_csv.exists():
            raise FileNotFoundError(f"Centers CSV file not found: {args.centers_csv}")
        
        # Extract sample name from stimulus file path
        sample_name = extract_sample_name_from_path(args.stimulus)
        print(f"Extracted sample name from path: {sample_name}")
        
        center_row, center_col = load_roi_center(args.centers_csv, args.roi, sample_name=sample_name)
        # Swap to (x, y) convention for SRF generation
        roi_center = (center_col, center_row)
        print(f"Loaded center for ROI {args.roi} (sample {sample_name}): x={roi_center[0]:.1f}, y={roi_center[1]:.1f}")
    
    # Generate spatial RF with same shape as stimulus frames
    print("Generating spatial receptive field...")
    srf = generate_spatial_rf(stimulus.shape[1:], srf_params, roi_center=roi_center)
    
    # Predict responses
    print("Predicting responses...")
    predicted = predict_responses(
        stimulus, srf, trf_time, trf_filter,
        stimulus_rate=effective_rate,
    )
    
    print(f"Predicted response shape: {predicted.shape}")
    print(f"Response range: [{predicted.min():.3f}, {predicted.max():.3f}]")
    
    # Save output
    if args.output is not None:
        np.save(args.output, predicted)
        print(f"Saved predicted responses to: {args.output}")
    
    # Display plot
    if args.plot:
        import matplotlib.pyplot as plt
        
        fig, axes = plt.subplots(1, 2, figsize=(12, 4))
        
        # Plot spatial RF
        axes[0].imshow(srf, cmap='viridis')
        axes[0].set_title('Spatial Receptive Field')
        axes[0].set_xlabel('X')
        axes[0].set_ylabel('Y')
        
        # Plot predicted response
        time_axis = np.arange(len(predicted)) / effective_rate
        axes[1].plot(time_axis, predicted, linewidth=2)
        axes[1].set_title('Predicted Response')
        axes[1].set_xlabel('Time (s)')
        axes[1].set_ylabel('Response')
        axes[1].grid(True, alpha=0.3)
        
        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    main()
